### ISSUE TITLE
request / response setup

### ISSUE THREAD

**Issue by percramer** [appccelerate/eventbroker#2]
Hi,

great product, let me start with that! I was wondering if you ever though about some kind of request / response for the library also? Which doesn't have to be async. In my software i have a plugin setup. So if a plugin needs something it will now just do a settings request and plugins that are attached to that event will check if they have got data for the requested setting and respond to it. It would be great if i could somehow create such a system with the event broker.

Regards,

Per

**Comment by ursenzler** [comment]
Hi Per

Thanks!

You can do that more or less already. Each subscriber can add data to the EventArguments. Just make sure that this communication is restricted to synchronous (see http://www.appccelerate.com/eventbrokerhandlers.html), so that the event invoker gets back the results.

The difference to async is that everything runs on the same thread and the event invoker is blocked.

Regards,
Urs

**Comment by percramer** [comment]
Hi Urs,

thank you for your quick answer. But if i fire an event directly on the broker (sync) will it how do i know then that it has passed all subscribers? Of is that event broker.fire blocking? Because if it is, then i must be doing something wrong in my tests :-)

**Comment by philippdolder** [comment]
Hi Per,

I'm quickly hopping in for Urs.

The synchronous handler returns the control flow back to the publisher only after all subscribers have finished execution. So yes, your caller is blocked until then.

Maybe you can post a gist sample and we'll try to help you figure out the issue with your tests.

Regards,
Philipp

**Comment by michaelestermann** [comment]
Due to inactivity, this issue has been closed. If the question is still not answered, consider reopening the issue again.
